"use client";

import { useMemo, useState } from "react";
import { formatINR } from "@/lib/calculations";

const slabs: Record<string, { name: string; monthly: number }> = { Maharashtra: { name: "Maharashtra", monthly: 200 }, Karnataka: { name: "Karnataka", monthly: 200 }, WestBengal: { name: "West Bengal", monthly: 200 }, Telangana: { name: "Telangana", monthly: 200 }, TamilNadu: { name: "Tamil Nadu", monthly: 0 }, Delhi: { name: "Delhi", monthly: 0 } };
export default function ProfessionalTaxCalculator() {
  const [state, setState] = useState("Maharashtra"); const [salary, setSalary] = useState(100000); const [current, setCurrent] = useState(200); const [employerShare, setEmployerShare] = useState(0);
  const result = useMemo(() => { const slab = slabs[state].monthly; const employeeCost = Math.max(0, current - employerShare); return { slab, monthlySavings: Math.max(0, current - slab), annual: employeeCost * 12, compliant: current <= slab + employerShare }; }, [state, current, employerShare]);
  return <div>
    <div className="mb-6"><p className="font-mono text-xs font-semibold uppercase tracking-[0.16em] text-primary">Professional tax impact</p><h2 className="mt-2 text-2xl font-bold text-foreground">Check your monthly salary-slip impact</h2><p className="mt-2 text-sm leading-6 text-muted">Professional tax is state-specific. Use this estimate to spot an incorrect deduction or understand the employer contribution shown on your payslip.</p></div>
    <div className="grid gap-4 md:grid-cols-2"><label className="flex flex-col gap-2 text-sm font-semibold text-foreground">State<select className="rounded-lg border border-border bg-card px-3 py-3" value={state} onChange={(event) => setState(event.target.value)}>{Object.entries(slabs).map(([key, value]) => <option key={key} value={key}>{value.name}</option>)}</select></label><label className="flex flex-col gap-2 text-sm font-semibold text-foreground">Monthly gross salary<input className="rounded-lg border border-border bg-card px-3 py-3" type="number" min="0" value={salary} onChange={(event) => setSalary(Number(event.target.value) || 0)} /></label><label className="flex flex-col gap-2 text-sm font-semibold text-foreground">Professional tax deducted<input className="rounded-lg border border-border bg-card px-3 py-3" type="number" min="0" value={current} onChange={(event) => setCurrent(Number(event.target.value) || 0)} /></label><label className="flex flex-col gap-2 text-sm font-semibold text-foreground">Employer-paid share<input className="rounded-lg border border-border bg-card px-3 py-3" type="number" min="0" value={employerShare} onChange={(event) => setEmployerShare(Number(event.target.value) || 0)} /></label></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-3"><Stat label="Indicative state cap" value={result.slab} /><Stat label="Potential monthly difference" value={result.monthlySavings} /><Stat label="Employee annual cost" value={result.annual} strong /></div>
    <p className="mt-5 rounded-lg bg-light-bg p-4 text-xs leading-5 text-muted">{result.compliant ? "Your entered deduction is within this simple indicative benchmark." : "Your entered deduction is above this simple benchmark—ask payroll for the applicable state slab and registration details."} Professional tax rules can include salary thresholds, February adjustments and state-specific exemptions.</p>
  </div>;
}
function Stat({ label, value, strong = false }: { label: string; value: number; strong?: boolean }) { return <div className={`rounded-xl border border-border p-4 ${strong ? "bg-light-bg" : "bg-card"}`}><p className="text-xs text-muted">{label}</p><p className={`mt-2 text-xl font-bold ${strong ? "text-primary" : "text-foreground"}`}>{formatINR(value)}</p></div>; }
