import type { Metadata } from "next";
import SEOArticlePage from "@/components/SEOArticlePage";
import SeverancePayCalculator from "@/components/SeverancePayCalculator";

export const metadata: Metadata = { title: "Severance Pay Calculator India: Notice Pay, Leave & Gratuity", description: "Estimate severance pay in India with notice pay, leave encashment, ex-gratia and gratuity components. Includes formulas, assumptions and FAQs." };
const sections = [
  { heading: "What is severance pay in India?", paragraphs: ["Severance pay is the amount an employee may receive when employment ends because of redundancy, restructuring, a separation agreement or another employer-led exit. India does not have one universal severance formula for every private-sector employee. The appointment letter, standing orders, company policy, settlement terms and applicable labour law all matter.", "This calculator separates common settlement components rather than presenting one guaranteed legal entitlement. Use it as a conversation starter with HR, payroll or an employment adviser."], bullets: ["Notice pay may replace some or all of a contractual notice period.", "Leave encashment is usually based on eligible unused leave and the employer's policy.", "Gratuity generally requires the relevant eligibility period and is calculated under the applicable rules."] },
  { heading: "How the estimate is calculated", paragraphs: ["The estimate uses a 26-day working-month convention for daily pay. It applies 15/26 × last drawn basic plus DA × completed years for a simple gratuity estimate after five years, then adds notice pay, leave encashment and any entered ex-gratia amount.", "Your actual full-and-final statement may include unpaid salary, incentives, deductions, loans, tax withholding, reimbursements or recoveries that this tool does not model."], bullets: ["Review whether your offer defines notice pay on gross salary or basic salary.", "Check if variable compensation is earned, payable or forfeited at exit.", "Ask for a component-wise settlement statement before signing a release."] },
  { heading: "Worked example", paragraphs: ["For ₹60,000 monthly basic salary, zero DA, five completed years, 60 notice days and 15 eligible leave days, the calculator shows separate estimates for gratuity, notice pay and leave encashment. The result changes immediately when you adjust the service period or salary basis.", "The example is intentionally transparent: a clean breakdown is more useful than an unexplained total, especially when comparing a negotiated exit package with your contractual benefits."] },
  { heading: "Tax and legal context", paragraphs: ["Severance, notice pay, leave encashment and gratuity can have different tax treatment depending on the facts and applicable exemptions. Do not treat the estimate as tax advice. Confirm the final treatment with payroll or a qualified tax professional.", "Never use this calculator to hide income, fabricate service records or avoid lawful deductions. It is designed for documentation, budgeting and informed questions." ] },
];
const faqs = [{ question: "Is severance pay mandatory in India?", answer: "Not in one uniform way for every employee. Entitlement can depend on the contract, separation reason, applicable labour law, company policy and settlement terms." }, { question: "Does severance include gratuity?", answer: "It can be shown alongside gratuity in a final settlement, but gratuity is a distinct statutory benefit with its own eligibility and calculation rules." }, { question: "Can I negotiate severance?", answer: "Some employer-led separation packages are negotiable. Ask for each component in writing and understand tax, notice and release implications before accepting." }];
export default function Page() { return <SEOArticlePage eyebrow="India salary guide / 2026" title="Severance Pay Calculator India" description={metadata.description as string} updated="August 2026" intro="Estimate common exit-payment components—notice pay, leave encashment, ex-gratia and gratuity—without confusing a planning estimate with a guaranteed legal entitlement." sections={sections} faqs={faqs} calculator={<SeverancePayCalculator />} related={[{ label: "Gratuity calculator", href: "/gratuity-calculator" }, { label: "Notice period calculator", href: "/notice-period-calculator" }, { label: "Salary breakup calculator", href: "/salary-breakup" }]} />; }
