import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer | SalaryScope",
  description: "Read our disclaimer regarding the use of SalaryScope calculators.",
  alternates: { canonical: "https://salaryscope.in/disclaimer" },
};

export default function DisclaimerPage() {
  return (
    <div className="py-12 px-4" style={{ backgroundColor: "#F5F7FA" }}>
      <div className="max-w-2xl mx-auto">
        <div className="bg-white rounded-xl p-8 shadow-sm" style={{ border: "1px solid #E5E7EB" }}>
          <h1 className="text-3xl font-bold mb-6" style={{ color: "#1A1A2E" }}>Disclaimer</h1>
          
          <div className="prose text-sm" style={{ color: "#1A1A2E", lineHeight: 1.8 }}>
            <p className="mb-4">
              <strong>SalaryScope is not an official government website.</strong> We are an independent platform 
              and are not affiliated, associated, authorized, endorsed by, or in any way officially connected 
              with any government body, ministry, or tax authority in India.
            </p>
            <p className="mb-4">
              All calculations and results provided on this website are estimates intended for planning and 
              informational purposes only. They do not constitute tax, financial, or legal advice.
            </p>
            <p className="mb-4">
              While we strive to keep the calculators updated with the latest rules for FY 2025-26, Indian tax 
              laws and payroll regulations are complex and subject to frequent changes. The information presented 
              here may not always reflect the most recent amendments or cover every unique edge case. Your actual 
              take-home salary, tax liability, or gratuity payout may differ based on your employer's specific 
              payroll structure, exact exemptions you claim, and final assessments by the Income Tax Department.
            </p>
            <p className="mb-4">
              Always verify your financial numbers with your company's Human Resources (HR) department, a 
              certified Chartered Accountant (CA), or a qualified tax professional before making any significant 
              financial decisions, negotiating job offers, or filing tax returns.
            </p>
            <p className="mb-4">
              SalaryScope and its creators are not responsible or liable for any errors, omissions, or any 
              decisions made or actions taken in reliance on the results generated by these calculators.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
