import type { Metadata } from "next";
import SalaryGuidePage from "@/components/SalaryGuidePage";
const guides: Record<string,{title:string;description:string;intro:string}>={
 'software-engineer-salary-bangalore':{title:'Software Engineer Salary in Bangalore',description:'Indicative Bangalore software engineer salary ranges by experience and market band.',intro:'Software engineer salaries in Bangalore vary widely across startups, product companies, services firms and global capability centres. The useful comparison is total fixed cash after understanding variable pay, employer PF and gratuity. These indicative bands give you a starting point for evaluating an offer, then the SalaryScope calculator turns the CTC into a monthly in-hand estimate.'},
 'software-engineer-salary-hyderabad':{title:'Software Engineer Salary in Hyderabad',description:'Indicative Hyderabad software engineer salary ranges and CTC context.',intro:'Hyderabad has a broad software market spanning product, services, fintech and enterprise technology employers. Salary depends on experience, stack, company tier and the fixed-to-variable mix. Use these directional bands to frame a conversation, then compare the actual take-home number rather than relying on headline CTC.'},
 'data-analyst-salary-india':{title:'Data Analyst Salary in India',description:'Data analyst salary ranges in India with practical CTC context.',intro:'Data analyst compensation in India changes with SQL, experimentation, product analytics, visualisation and domain depth. Entry-level roles may have modest fixed pay while experienced analysts and analytics engineers can command wider ranges. Compare the complete offer structure and estimate monthly in-hand before making a move.'},
 'tcs-fresher-salary':{title:'TCS Fresher Salary: CTC and In-Hand Estimate',description:'Understand indicative TCS fresher CTC, deductions and monthly in-hand salary.',intro:'TCS fresher compensation is often discussed as a single CTC figure, but monthly cash depends on the salary breakup, PF, professional tax, tax regime and any variable component. This guide explains how to interpret an indicative offer without presenting unofficial figures as an employer commitment.'},
 'product-vs-service-company-salary':{title:'Product vs Service Company Salary in India',description:'Compare product and service company salary structures beyond headline CTC.',intro:'Product and service companies can differ in fixed pay, variable pay, equity, promotion cycles, work location and role scope. A higher CTC is not always higher monthly cash. Compare fixed compensation and use a consistent salary calculator before weighing growth and learning opportunities.'},
 'ctc-vs-in-hand-salary':{title:'CTC vs In-Hand Salary: What Is the Difference?',description:'A practical guide to CTC, gross salary, deductions and monthly take-home pay in India.',intro:'CTC is not the same as take-home pay. Employer PF, gratuity provisions, variable pay and deductions can create a meaningful gap between an offer letter and your bank credit. This guide explains each layer and shows why the salary breakup matters when you budget or compare offers.'},
};
export function generateStaticParams(){return Object.keys(guides).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const guide=guides[slug];return guide?{title:guide.title,description:guide.description}:{title:'Salary Guide India'};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const guide=guides[slug]??guides['ctc-vs-in-hand-salary'];return <SalaryGuidePage title={guide.title} intro={guide.intro}/>}
